GET {{host}}{{apiUri}}/posts/feed
Accept: application/json
Authorization: {{authorization}}

###
POST {{host}}{{apiUri}}/post/create
Content-Type: application/json
Accept: application/json
Authorization: {{authorization}}

{
    "text": "Animi quibusdam ut voluptas eaque dolore officia."
}
