### регистрация
POST http://127.0.0.1:8001/api/register
Accept: application/json
Content-Type: application/json

{
    "login": "User1",
    "email": "email@email.ru",
    "password": "password",
    "confirm_password": "password",
    "first_name": "first_name",
    "last_name": "last_name",
    "birthday": "1970-01-01",
    "sex": 1,
    "interests": "interests",
    "city": "city"
}

### получить пользователя
GET http://127.0.0.1:8001/api/user/1
Accept: application/json
Content-Type: application/json
